Fix RefreshToken Issue
Team-Ampersand/GKR-Frontend pull request #91
Opened 2023-12-23 18:27 UTC by mini-aron

### 개요
+ accessToken이 재발급 되지 않는 문제가 발생헀습니다.

### 작업사항
+ accessToken이 재발급 되지 않는 문제를 해결했습니다.
+ 제재 리스트의 스타일을 수정했습니다.
+ 공지페이지의 미리보기가 잘리는 문제를 해결했습니다.
### 변경로직

### 기타

2023-12-24 10:46 UTC, baekteun commented on src/components/Promotion/organisms/index.tsx
> +    if (IsLogined()) router.push('/home')
사소한거긴한테 문법상 isLoggedIn이 맞는거로 알아요

2023-12-24 10:48 UTC, baekteun commented on src/utils/libs/apiClient.ts
> +  headers: BASE_HEADER,
위에있는 apiClient랑 차이가 무엇인가요?

2023-12-24 10:55 UTC, mini-aron commented on src/utils/libs/apiClient.ts
> +  headers: BASE_HEADER,
interceptors의 유무입니다

2023-12-24 10:56 UTC, mini-aron commented on src/components/Promotion/organisms/index.tsx
> +    if (IsLogined()) router.push('/home')
수정하겠습니다
알려주셔서 감사합니다

2023-12-24 10:56 UTC, baekteun commented on src/utils/libs/apiClient.ts
> +  headers: BASE_HEADER,
apiClient와 api로만 둔다면 둘의 차이에 혼동이 올 가능성이 높다고 생각되는데 이 점을 해결할 방안이 없을까요?

2023-12-24 10:57 UTC, mini-aron commented on src/utils/libs/apiClient.ts
> +  headers: BASE_HEADER,
interceptors의 내부조건문을 다시 수정해보겠습니다!

2023-12-24 14:38 UTC, apnalkkamkkamhanjoon requested changes

2023-12-24 14:38 UTC, apnalkkamkkamhanjoon commented on src/components/Violation/organisms/index.tsx
> +      <TopBox text="제재 내역" />
음 저희 prettier 홀따옴표 아니였나요?

2023-12-24 14:38 UTC, apnalkkamkkamhanjoon commented on src/components/common/atoms/LoginButton/index.tsx
> +    router.push('/')
push가 GAuth Redirect URI로 이동해야되는 것 아닌가요?

2023-12-24 14:38 UTC, apnalkkamkkamhanjoon commented on src/utils/libs/getRefresh.ts
> +  console.log(config)
콘솔 제거해주세요

2023-12-24 14:38 UTC, apnalkkamkkamhanjoon commented on src/utils/libs/getRefresh.ts
> +  } else if (!AccessToken && !config.url?.includes('auth')) {
/auth로 하는게 더 좋은 표현법 같아요

2023-12-24 14:38 UTC, apnalkkamkkamhanjoon commented on src/utils/libs/getToken.ts
> -    else if (!AccessToken) {
토큰을 재발급 받는 로직이 여기서 작동하는데 이 조건문을 삭제하신 이유는 뭔가요

2023-12-24 14:41 UTC, mini-aron commented on src/utils/libs/getRefresh.ts
> +  } else if (!AccessToken && !config.url?.includes('auth')) {
config를 console로 조회하였을때 url이 "/auth"가 아닌 "auth"로 조회되기때문에 저렇게 작성하였습니다

2023-12-24 14:42 UTC, mini-aron commented on src/components/common/atoms/LoginButton/index.tsx
> +    router.push('/')
수정하겠습니다

2023-12-24 14:45 UTC, apnalkkamkkamhanjoon commented on src/utils/libs/getRefresh.ts
> +  } else if (!AccessToken && !config.url?.includes('auth')) {
음 'auth'가 맞는 표현인가보군요

2023-12-24 14:52 UTC, mini-aron commented on src/utils/libs/getToken.ts
> -    else if (!AccessToken) {
getRefresh에서 이미 토큰재발급 로직이 작성되어있어 중복호출을 하기때문에 제거했습니다

2023-12-24 14:52 UTC, mini-aron commented on src/components/Violation/organisms/index.tsx
> +      <TopBox text="제재 내역" />
속성값은 큰따옴표입니다!

2023-12-24 14:52 UTC, mini-aron commented on src/utils/libs/getRefresh.ts
> +  console.log(config)
넹

2023-12-24 15:02 UTC, mini-aron commented on src/components/Violation/organisms/index.tsx
> +      <TopBox text="제재 내역" />
수정하겠습니다

2023-12-25 12:55 UTC, apnalkkamkkamhanjoon approved these changes

2023-12-25 13:06 UTC, merged